server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service-route
              uri: lb://auth-service
              predicates:
                - Path=/api/v1/auth/**,  /api/v1/users/**
              filters:
                - name: JwtAuthenticationFilterFactory

            - id: restaurant-service-route
              uri: lb://restaurant-service
              predicates:
                - Path=/api/v1/restaurants/**
              filters:
                - name: JwtAuthenticationFilterFactory

            - id: order-service-route
              uri: lb://order-service
              predicates:
                - Path=/api/v1/orders/**
              filters:
                - name: JwtAuthenticationFilterFactory

            - id: notification-service-route
              uri: lb://notification-service
              predicates:
                - Path=/api/v1/notifications/**
              filters:
                - name: JwtAuthenticationFilterFactory

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health, info

jwt:
  secret: Z8VZeLzVDBzzH6D2UG9LVHsYdls8dnvzwc3nX5kj2Tc=
