server:
  port: 8084

spring:
  mail:
    host: smtp.gmail.com
    port: 465
    username: ea.main.app@gmail.com
    password: pbqyqchegnnlkcex
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    queue:
      order.placed: order.placed.notification
      exchange: order.events

mail:
  from: ea.main.app@gmail.com

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health, info
